### ISSUE TITLE
Authentication complete

### ISSUE THREAD

**Issue by jfeng702** [jfeng702/Slice#1]
Hi Stephen,

I am finished with Authentication, please take a look.

Thanks!
Joey

**Comment by s-pangburn** [comment]
Hey Joey! Good work! It looks like it's starting to come together! There are a few things that need tweaking before I can mark this feature complete, however:

- [ ] You should definitely have a logo in the top left corner. Your site looks "incomplete" because most people expect that to be there.
- [ ] "Capture moments in life..." <-- I think this looks slightly better on the page when it's italicized, but that's just my personal opinion.
- [ ] Your signup and login buttons should have a little more margin on the top. They shouldn't be touching the top of the page. Also it'd be nice if they were a little bigger/had just a little more padding between the text and the edges of the button. Use Flickr's nav bar as a reference!
- [ ] When the modal pops up, the first input field should autofocus. Google how to do this, and let me know if you have trouble. (A lifecycle method should help you a lot here!)
- [ ] When I click "Demo" on the signup page, I get "Username has already been taken. Make sure you're dispatching the "login" action regardless of which form you are on.
- [ ] There should be a link on your modal to switch between login and signup.
- [ ] Errors should clear when the modal disappears
- [ ] When I close the signup modal and open the login modal, the errors from signup are still there
- [ ] Your errors should be red or some other standout color, probably.
- [ ] I'm not sure how you have the modal positioned, but it seems to jump further down the page the more errors there are. I'm not just meaning that it gets bigger, I mean the whole modal moves down. It looks a little strange.
- [ ] The modal needs a little more styling. Use Flickr's [signup form](https://login.yahoo.com/account/create?specId=usernameReg&src=flickr&done=https%3A%2F%2Fapi.login.yahoo.com%2Foauth2%2Frequest_auth%3Fclient_id%3Ddj0yJmk9NTJmMkVmOFo3RUVmJmQ9WVdrOVdXeGhVMWx3TjJFbWNHbzlNQS0tJnM9Y29uc3VtZXJzZWNyZXQmeD01OA--%26redirect_uri%3Dhttps%253A%252F%252Fwww.flickr.com%252Fsignin%252Fyahoo%252Foauth%252F%253Fsignup%253D1%26response_type%3Dcode%26scope%3Dopenid%252Csdpp-w%26nonce%3Dbde2934f666e9784b09d0f24abe6d14e) as reference for about how wide it should be/the spacing between elements. The input boxes should stretch across the whole modal (not counting the padding) Ideally, it should look exactly like that signup form (with fewer input fields, of course)
   - [ ] If you want to have placeholder text the way Flickr does in its signup form, Google the html attribute `placeholder` 🙂 

Let me know if you have any trouble with any of these and I'll do my best to help. Best of luck!

**Comment by jfeng702** [comment]
Hi Stephen,

The form authentication edits should have been made. Let me know what you think. Have a good weekend!

**Comment by s-pangburn** [comment]
Excellent work Joey! This is looking really good!

- [ ] Slice logo should stay the same size after logging in.
- [ ] Slice logo should link to "/"
- [ ] https://slice-app.herokuapp.com/#/dlskfjdslkfjsldfjlksjf <-- This should redirect to the splash page if you are logged out or the homepage if you are logged in (sorry, just a convention App Academy enforces)
- [ ] `Sign up` and `Log in` buttons should set `cursor: pointer` on hover (CSS)
  - Also experiment with changing the background color so that it highlights a little bit when you hover over it. I think this could look really nice, specially if you use `rgba` to set the background as semi-transparent! I personally think white looks nice, but feel free to go for something a little more subtle, like semi-transparent black?
- [ ] Username and Password input fields should have a little spacing between them.
- [ ] Also make your Username and Password inputs `40px` in height. It makes things feel a little less cramped together.
- [ ] Demo Login button should look identical to the Submit button
- [ ] Submit and Demo Login should both `cursor: pointer` on hover.
- [ ] Your errors currently overlap your input fields:
![screen shot 2018-02-05 at 9 11 34 am](https://user-images.githubusercontent.com/8031316/35818346-a3d3b850-0a54-11e8-9bfd-9b6700ff2ccb.png)
  - You should set up the spacing on the form so that there is room for errors. Maybe leaving a little room on the bottom can work as well, if you don't want to space out the top too much.
- [ ] After logging in, your Logout button and your "Welcome!" message should be properly spaced, not hanging out in the corner like that.
- [ ] Your Welcome text needs to be a bit lighter, it's hard to read right now.
- [ ] Logout button should look reminiscent of your Sign up and Log in buttons
- [ ] Your demo user probably shouldn't be called "username", just almost seems like a bug, even though it isn't? Try something like "Demo User" or "John Doe" or some other generic name.

Please let me know if you have questions about any of these!
