### ISSUE TITLE
Comments ready for review

### ISSUE THREAD

**Issue by jfeng702** [jfeng702/Slice#3]

**Comment by s-pangburn** [comment]
Great work Joey! Most of my feedback has to do with styling, along with a couple minor points

- [ ] I should be able to delete a comment
- [ ] Either make the comment input a `<textarea>` or don't make it so tall.
- [ ] I should see my comment as soon as I create it (scroll down or place comments above input
- [ ] Edit form button should `cursor: pointer` on hover
- [ ] New comment always seems to replace last comment made
- [ ] I only see edit and not delete
- [ ] Reposition edit button, it looks like it's for the comment, not the photo
- [x] Redo seed data to `destroy_all`
- [ ] Title and description of each photo should be a little bigger
- [ ] Center gallery view

**Comment by jfeng702** [comment]
Hi Stephen,

All these action items for comments should now be complete. Let me know your thoughts. Thanks!

**Comment by s-pangburn** [comment]
- [ ] Comments should wrap
- [ ] Ideally there should be some whitespace on the bottom of the page so that the lowest comment isn't touching the bottom of the screen when you scroll all the way down.

That's it! These are relatively minor points, so I'm going to mark this issue as complete. Great work Joey!
